Spesing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView, AboutPageView, custom_404, custom_500
from users import urls as user_urls
from spese import urls as spese_urls


# Custom Errors
handler404 = 'Spesing.views.custom_404'
handler500 = 'Spesing.views.custom_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='homepage'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('user/', include(user_urls), name='users'),
    path('spese/', include(spese_urls), name='spese'),
    # Da togliere quando si finisce di testare e di fare il layout
    path('error404/', custom_404, name='custom_error_404'),
    path('error500/', custom_500, name='custom_error_500')
]

spese/urls.py
from django.urls import path
from . import views

app_name = 'spese'

urlpatterns = [
    path('home', views.HomeSpese.as_view(), name='home'),
    path('macrocategorie-list/', views.MacroCategorieListView.as_view(), name='macro-list'),
    path('categorie-list/<int:macro_id>/', views.CategorieListView.as_view(), name='categorie-list'),
    path('list/<int:categoria_id>', views.SpeseListView.as_view(), name='list'),
    path('list/', views.AllSpeseListView.as_view(), name='all-list'),
    path('create/', views.SpesaCreateView.as_view(), name='create'),
    path('delete/<pk>', views.SpesaDeleteView.as_view(), name='delete'),
    path('details/<pk>', views.SpesaDetailView.as_view(), name='details'),
    path('update/<pk>', views.SpesaUpdateView.as_view(), name='update'),
]

spese/models.py
import uuid
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

__all__ = ["Abbonamento", 'MacroCategoria', 'Categoria', 'Spesa']


class Abbonamento(models.Model):
    tipologia = models.CharField(max_length=40)

    class Meta:
        verbose_name = 'Abbonamento'
        verbose_name_plural = 'Abbonamenti'

    def __str__(self):
        return self.tipologia


class MacroCategoria(models.Model):
    titolo = models.CharField(max_length=40)
    descrizione = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Macro Categoria'
        verbose_name_plural = 'Macro Categorie'

    def __str__(self):
        return self.titolo


class Categoria(models.Model):
    macro = models.ForeignKey(MacroCategoria, on_delete=models.CASCADE, default='')
    nome = models.CharField(max_length=40)
    descrizione = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorie'

    def __str__(self):
        return self.nome


class Spesa(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    proprietario = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    nome = models.CharField(max_length=50)
    importo = models.DecimalField(max_digits=8, decimal_places=2)
    data_acquisto = models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, default='', null=True, blank=True)
    abbonamento = models.ForeignKey(Abbonamento, on_delete=models.CASCADE, default='')
    descrizione = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Spesa'
        verbose_name_plural = 'Spese'

    def __str__(self):
        return self.nome

    def totale_spese(self):
        spese_utente = Spesa.objects.filter(proprietario=self.proprietario)
        totale = 0
        if len(spese_utente) > 0:
            for spesa in spese_utente:
                totale += spesa.importo
            totale = str(round(totale, 2)) + "€"
            return totale
        else:
            return str(totale)

    def totale_spese_mensile(self):
        spese_utente_mensile = Spesa.objects.filter(proprietario=self.proprietario, abbonamento__tipologia="Mensile")
        totale = 0
        if len(spese_utente_mensile) > 0:
            for spesa in spese_utente_mensile:
                totale += spesa.importo
            totale = str(round(totale, 2)) + "€"
        else:
            totale = str(totale) + "€"
        return totale

    def totale_spese_annuale(self):
        spese_utente_annuale = Spesa.objects.filter(proprietario=self.proprietario, abbonamento__tipologia="Annuale")
        totale = 0
        if len(spese_utente_annuale) > 0:
            for spesa in spese_utente_annuale:
                totale += spesa.importo
            totale = str(round(totale, 2)) + "€"
        else:
            totale = str(totale) + "€"
        return totale

    def n_spese(self):
        spese_utente = Spesa.objects.filter(proprietario=self.proprietario)
        n_spese_utente = len(spese_utente)
        return n_spese_utente

spese/views.py
import uuid
from django.contrib.auth.decorators import login_required
from django.forms import DateInput
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from spese.models import MacroCategoria, Categoria, Spesa

# Create your views here.
__all__ = ["MacroCategorieListView",
           "CategorieListView",
           "SpeseListView",
           "AllSpeseListView",
           "SpesaDetailView",
           "SpesaUpdateView",
           "SpesaCreateView",
           "SpesaDeleteView"
           ]


@method_decorator(login_required, name="dispatch")
class HomeSpese(ListView):
    model = Spesa
    template_name = "spese/home_spese.html"

    def get_queryset(self):
        return super().get_queryset().filter(proprietario=self.request.user)


@method_decorator(login_required, name='dispatch')
class MacroCategorieListView(ListView):
    model = MacroCategoria
    template_name = 'spese/macro_list.html'


@method_decorator(login_required, name='dispatch')
class CategorieListView(ListView):
    model = Categoria
    template_name = 'spese/categorie_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(macro_id=self.kwargs['macro_id'])


@method_decorator(login_required, name='dispatch')
class SpeseListView(ListView):
    paginate_by = 5
    model = Spesa
    template_name = 'spese/spese_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(proprietario=self.request.user).filter(
            categoria_id=self.kwargs['categoria_id'])


@method_decorator(login_required, name='dispatch')
class AllSpeseListView(ListView):
    paginate_by = 5
    model = Spesa
    template_name = 'spese/spese_list.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(proprietario=self.request.user)
        filtro_data = self.request.GET.get('filtro_data', None)
        if filtro_data:
            order_mapping = {
                'decrescente': '-data_acquisto',
                'crescente': 'data_acquisto',
            }
            order_by = order_mapping.get(filtro_data, 'data_acquisto')
            queryset = queryset.order_by(order_by)

        filtro_importo = self.request.GET.get('filtro_importo', None)
        if filtro_importo:
            order_mapping = {
                'decrescente': '-importo',
                'crescente': 'importo',
            }
            order_by = order_mapping.get(filtro_importo, 'importo')
            queryset = queryset.order_by(order_by)
        return queryset


@method_decorator(login_required, name='dispatch')
class SpesaDetailView(DetailView):
    model = Spesa


@method_decorator(login_required, name='dispatch')
class SpesaUpdateView(UpdateView):
    model = Spesa
    fields = ["nome", "importo", "data_acquisto", "categoria", "abbonamento", "descrizione"]
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("spese:all-list")


@method_decorator(login_required, name='dispatch')
class SpesaCreateView(CreateView):
    model = Spesa
    fields = ["nome", "importo", "data_acquisto", "categoria", "abbonamento", "descrizione"]
    template_name_suffix = "_create_form"
    success_url = reverse_lazy("spese:all-list")

    def form_valid(self, form):
        form.instance.id = uuid.uuid4()
        form.instance.proprietario = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['data_acquisto'].widget = DateInput(attrs={'type': 'date'})
        return form


@method_decorator(login_required, name='dispatch')
class SpesaDeleteView(DeleteView):
    model = Spesa
    success_url = reverse_lazy("spese:all-list")

spese/templates/spese/categorie_list.html
{% extends "base.html"%}

{% block title %}Categorie{% endblock %}

{% block content %}
    <section class="container text-center">
        <h2>LISTA CATEGORIE</h2>
        <div class="row gap-4 pt-4 d-flex align-center justify-content-center">
            {% if user.is_authenticated %}
                {% if categoria_list %}
                    {% for categoria in categoria_list %}
                        <div class="col-xs-10 col-sm-5 col-md-5 col-xl-2">
                                <a href="{% url 'spese:list' categoria_id=categoria.id %}" class="btn btn-primary w-100">{{ categoria.nome }}</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Non ci sono categorie</p>
                {% endif %}
            {% endif %}
        </div>
    </section>
{% endblock %}

spese/templates/spese/home_spese.html
{% extends "base.html"%}

{% block title %}Home Spese{% endblock %}

{% block content %}
    <section class="container vh-75 d-flex flex-column align-items-center justify-content-center">
        <h2>Benvenuto {{ user.get_username.capitalize }}</h2>
        <div class="my-4 w-100 d-flex flex-column align-items-center justify-content-center gap-4">
            {% if spesa_list.count > 0 %}
                <div class="card p-0">
                  <div class="card-header">
                    INFO SPESE
                  </div>
                        <ul class="list-group list-group-flush mx-4 my-2">
                            <li class="list-group-item">N° Spese: {{ spesa_list.0.n_spese }}</li>
                            <li class="list-group-item">Tot. spese: {{ spesa_list.0.totale_spese }}</li>
                            <li class="list-group-item">Tot. mensile: {{ spesa_list.0.totale_spese_mensile }}</li>
                            <li class="list-group-item">Tot. annuale: {{ spesa_list.0.totale_spese_annuale }}</li>
                        </ul>
                </div>
            {% endif %}
            <div class="container row d-flex align-items-center justify-content-center gap-3">
                <a href="{% url 'spese:all-list' %}" class="btn btn-primary col-sm-3 col-lg-2 myAction">Vedi Spese</a>
                <a href="{% url 'spese:macro-list' %}" class="btn btn-secondary col-sm-4 col-lg-2 myAction">Macrocategorie</a>
                <a href="{% url 'spese:create' %}" class="btn btn-secondary col-sm-3 col-lg-2 myAction">Nuova Spesa</a>
            </div>
        </div>
    </section>
{% endblock %}

spese/templates/spese/macro_list.html
{% extends "base.html"%}

{% block title %}Macro Categorie{% endblock %}

{% block content %}
    <section class="container text-center">
        <h2>LISTA MACRO CATEGORIE</h2>
        <div class="row gap-4 pt-4 d-flex align-center justify-content-center">
            {% if user.is_authenticated %}
                {% if macrocategoria_list %}
                    {% for macro in macrocategoria_list %}
                        <div class="col-xs-10 col-sm-5 col-md-5 col-xl-2">
                                <a href="{% url 'spese:categorie-list' macro_id=macro.id %}" class="btn btn-primary w-100">{{ macro.titolo }}</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Non ci sono macro categorie</p>
                {% endif %}
            {% endif %}
        </div>
    </section>
{% endblock %}

spese/templates/spese/spesa_create_form.html
{% extends "base.html"%}
{% load crispy_forms_filters %}

{% block title %}Nuova Spesa{% endblock %}

{% block content %}
    <h2>NUOVA SPESA</h2>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex align-center justify-content-center">
                <input class="btn btn-secondary" type="submit" value="Crea">
            </div>
        </form>
    {% endif %}
{% endblock %}

spese/templates/spese/spesa_detail.html
{% extends "base.html"%}

{% block title %}Dettagli Spesa{% endblock %}

{% block content %}
    <div class="container row">
        <div class="col-12 col-lg-5 container h-100 py-3">
            <div class="card text-center">
              <article class="card-header">
                  <h5 class="card-title my-2">{{ spesa.nome }}</h5>
              </article>
              <div class="card-body">
                <a href="{% url 'spese:all-list' %}" class="btn btn-secondary"><i class="bi bi-arrow-left"></i></a>
                <a href="{% url 'spese:update' spesa.pk %}" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
              </div>
            </div>
        </div>
        <div class="col-12 col-lg-5 container h-100 py-3">
            <div class="card">
              <div class="card-header">
                INFO
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Categoria: {{ spesa.categoria }}</li>
                <li class="list-group-item">Data: {{ spesa.data_acquisto }}</li>
                <li class="list-group-item">Abbonamento: {{ spesa.abbonamento }}</li>
                <li class="list-group-item">Importo: {{ spesa.importo }} €</li>
                <li class="list-group-item">Descrizione: {{ spesa.descrizione }}</li>
              </ul>
            </div>
        </div>
    </div>
{% endblock %}

spese/templates/spese/spesa_update_form.html
{% extends "base.html"%}
{% load crispy_forms_filters %}

{% block title %}Aggiorna Spesa{% endblock %}

{% block content %}
    <h2>AGGIORNA SPESA</h2>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex align-center justify-content-center">
                <input class="btn btn-secondary" type="submit" value="Aggiorna">
            </div>
        </form>
    {% endif %}
{% endblock %}

spese/templates/spese/spese_list.html
{% extends "base.html"%}

{% block title %}Spese{% endblock %}

{% block content %}
    <section class="container">
        <div class="d-flex gap-4 align-items-center">
            <h2 class="m-0">LISTA SPESE</h2>
            <a href="{% url 'spese:create' %}" class="btn btn-primary my-3"><i class="bi bi-plus-lg"></i></a>
        </div>
        {% if spesa_list %}
            <table class="table w-100">
              <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">Importo</th>
                  <th scope="col" class="d-none d-md-table-cell">Data</th>
                  <th scope="col" class="d-none d-lg-table-cell">Categoria</th>
                  <th scope="col">Azioni</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <td></td>
                    <td class="fs-5"><a href="?filtro_importo=crescente"><i class="bi bi-caret-up-fill"></i></a> <a href="?filtro_importo=decrescente"><i class="bi bi-caret-down-fill"></i></a></td>
                    <td class="d-none d-md-table-cell fs-5"><a href="?filtro_data=crescente"><i class="bi bi-caret-up-fill"></i></a> <a href="?filtro_data=decrescente"><i class="bi bi-caret-down-fill"></i></a></td>
                    <td class="d-none d-lg-table-cell"></td>
                    <td></td>
                </tr>
                {% for spesa in page_obj %}
                <tr>
                  <td>{{ spesa.nome }}</td>
                  <td>{{ spesa.importo }} €</td>
                  <td class="d-none d-md-table-cell">{{ spesa.data_acquisto }}</td>
                  <td class="d-none d-lg-table-cell">{{ spesa.categoria.nome }}</td>
                  <td>
                      <div class="d-flex gap-2">
                        <div class="btn-group dropdown-center d-md-none">
                          <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-tools"></i>
                          </button>
                          <ul class="dropdown-menu p-3">
                            <li class="d-flex align-items-center justify-content-center"><a href="{% url 'spese:details' spesa.pk %}" class="btn btn-secondary"><i class="bi bi-info-circle-fill"></i></a></li>
                            <li class="d-flex align-items-center justify-content-center my-3"><a href="{% url 'spese:update' spesa.pk %}" class="btn btn-success"><i class="bi bi-pencil-square"></i></a></li>
                            <li class="d-flex align-items-center justify-content-center"><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#{{ spesa.pk }}">
                                    <i class="bi bi-trash-fill"></i>
                                </button>
                            </li>
                          </ul>
                        </div>
                        <a href="{% url 'spese:details' spesa.pk %}" class="btn btn-secondary d-none d-md-block"><i class="bi bi-info-circle-fill"></i></a>
                        <a href="{% url 'spese:update' spesa.pk %}" class="btn btn-success d-none d-md-block"><i class="bi bi-pencil-square"></i></a>
                        <!-- Button that opens a modal -->
                        <button type="button" class="btn btn-danger d-none d-md-block" data-bs-toggle="modal" data-bs-target="#{{ spesa.pk }}">
                            <i class="bi bi-trash-fill"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="{{ spesa.pk }}" data-bs-backdrop="static"
                             data-bs-keyboard="false" tabindex="-1" aria-labelledby="{{ spesa.pk }}" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title">Eliminare {{ spesa.nome }}?</h5>
                              </div>
                              <form action="{% url 'spese:delete' spesa.pk %}" method="POST">
                                  <div class="modal-body">
                                    <p>Sicuro di voler eliminare "{{ spesa.nome }}"?</p>
                                        {% csrf_token %}
                                        {{ form }}
                                  </div>
                                  <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                                      <button type="submit" class="btn btn-danger" value="Confirm">Elimina</button>
                                  </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!-- Pagination -->
            <div>
                <ul class="pagination d-flex align-center justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                          </a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                      {% if page_obj.number == num %}
                          <li class="page-item"><a class="page-link bg-dark-subtle text-secondary" href="?page={{ num }}">{{ num }}</a></li>
                      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                        </li>
                    {% endif %}
                  </ul>
            </div>
        {% else %}
            <p class="my-5">Non ci sono spese</p>
        {% endif %}
    </section>
{% endblock %}