Spesing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView, AboutPageView, custom_404, custom_500
from users import urls as user_urls
from spese import urls as spese_urls


# Custom Errors
handler404 = 'Spesing.views.custom_404'
handler500 = 'Spesing.views.custom_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='homepage'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('user/', include(user_urls), name='users'),
    path('spese/', include(spese_urls), name='spese'),
    # Da togliere quando si finisce di testare e di fare il layout
    path('error404/', custom_404, name='custom_error_404'),
    path('error500/', custom_500, name='custom_error_500')
]

spese/urls.py
from django.urls import path
from . import views

app_name = 'spese'

urlpatterns = [
    path('home', views.HomeSpese.as_view(), name='home'),
    path('macrocategorie-list/', views.MacroCategorieListView.as_view(), name='macro-list'),
    path('categorie-list/<int:macro_id>/', views.CategorieListView.as_view(), name='categorie-list'),
    path('list/<int:categoria_id>', views.SpeseListView.as_view(), name='list'),
    path('list/', views.AllSpeseListView.as_view(), name='all-list'),
    path('create/', views.SpesaCreateView.as_view(), name='create'),
    path('delete/<pk>', views.SpesaDeleteView.as_view(), name='delete'),
    path('details/<pk>', views.SpesaDetailView.as_view(), name='details'),
    path('update/<pk>', views.SpesaUpdateView.as_view(), name='update'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterCreateView.as_view(), name='register'),
    path('login/', views.LoginAuthView.as_view(), name='login'),
    path('logout/', views.LogoutAuthView.as_view(), name='logout'),
]

templates/about.html
{% extends "base.html"%}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="container">
        <section class="text-center bg-body-tertiary text-body rounded-3 p-5">
            <h2 class="pb-2 fw-bold">ABOUT US</h2>
            <p class="my-1">Anche se... dove sono le nostre facce?</p>
            <p class="mb-2">Forse serve un errore per trovarle!</p>
            <article class="py-4">
                <h3 class="pb-3">BACK-END</h3>
                <div class="d-flex align-center justify-content-center flex-wrap gap-5">
                    <div class="bg-body-secondary p-3 rounded-3" title="Menzione D'onore">
                        <figure class="position-relative m-0">
                            <img class="about-img rounded-circle" src="{% static 'img/pek-about.jpg' %}" alt="Alessandro Pecchini">
                            <div class="bedge rounded-circle"><i class="bi bi-star-fill p-0 m-0"></i></div>
                            <figcaption>Alessandro<br>Pecchini</figcaption>
                        </figure>
                    </div>
                    <div class="bg-body-secondary p-3 rounded-3" title="Menzione D'onore">
                        <figure class="position-relative m-0">
                            <img class="about-img rounded-circle" src="{% static 'img/roby-about.jpg' %}" alt="Roberto Spadoni">
                            <div class="bedge rounded-circle"><i class="bi bi-star-fill p-0 m-0"></i></div>
                            <figcaption>Roberto<br>Spadoni</figcaption>
                        </figure>
                    </div>
                </div>
            </article>
            <article class="pt-2">
                <h3 class="pb-3">FRONT-END</h3>
                <div class="d-flex align-center justify-content-center flex-wrap gap-5">
                    <div class="bg-body-secondary p-3 rounded-3" title="Menzione D'onore">
                        <figure class="position-relative m-0">
                            <img class="about-img rounded-circle" src="{% static 'img/pek-about.jpg' %}" alt="Alessandro Pecchini">
                            <div class="bedge rounded-circle"><i class="bi bi-star-fill p-0 m-0"></i></div>
                            <figcaption>Alessandro<br>Pecchini</figcaption>
                        </figure>
                    </div>
                    <div class="bg-body-secondary p-3 rounded-3" title="Menzione D'onore">
                        <figure class="position-relative m-0">
                            <img class="about-img rounded-circle" src="{% static 'img/roby-about.jpg' %}" alt="Roberto Spadoni">
                            <div class="bedge rounded-circle"><i class="bi bi-star-fill p-0 m-0"></i></div>
                            <figcaption>Roberto<br>Spadoni</figcaption>
                        </figure>
                    </div>
                    <figure class="bg-body-secondary p-3 rounded-3 m-0">
                        <img class="about-img rounded-circle" src="{% static 'img/sevy-about.jpg' %}" alt="Sebastiano Cassanelli">
                        <figcaption>Sebastiano<br>Cassanelli</figcaption>
                    </figure>
                    <figure class="bg-body-secondary p-3 rounded-3 m-0">
                        <img class="about-img rounded-circle" src="{% static 'img/fmammi-about.jpg' %}" alt="Francesco Mammi">
                        <figcaption>Francesco<br>Mammi</figcaption>
                    </figure>
                </div>
            </article>
        </section>
    </div>
{% endblock %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="it" data-bs-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <!-- LINK -->
        <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/open_dyslexic_font.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="{% static 'css/base_style.css' %}" id="base_css">
        <!-- SCRIPT -->
        <script src="{% static 'js/dark_mode.js' %}" defer></script>
        <script src="{% static 'js/dyslexic_accessibility.js' %}" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
        <script src="{% static 'js/ajax_calls.js' %}" defer></script>{% block head %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top navbar-expand-lg border-bottom border-body">
            <div class="container-fluid px-4">
                <!-- DROPDOWN MOBILE -->
                <div class="btn-group">
                    <!-- BOTTONE UTENTE -->
                    <button type="button" class="btn btn-outline-secondary rounded d-lg-none" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        <i class="bi bi-person-fill"></i>
                    </button>
                    <!-- DROPDOWN UTENTE -->
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
                      <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                      {% if user.is_authenticated %}<li><hr class="dropdown-divider"></li>
                      <li>
                        <form action="{% url 'users:logout' %}" method="POST">
                         {% csrf_token %}
                         <button type="submit" class="dropdown-item">Logout</button>
                        </form>
                      </li>
                      {% if user.is_staff %}<li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>{% endif %}{% endif %}
                    </ul>
                </div>
                <!-- DIV DEL LOGO -->
                <div class="logo-wrapper d-flex align-center d-md-flex justify-content-md-start">
                    <a class="navbar-brand p-0 d-flex" href="{% url 'homepage' %}">
                        <img class="myLogoNav" src="{% static 'img/logo-spesing1.svg' %}" alt="Logo del sito: Spesing">
                    </a>
                </div>
                <!-- BURGER MENU -->
                <button class="navbar-toggler px-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon">
                  </span>
                </button>
                <!-- LINK -->
                <div class="collapse navbar-collapse text-end" id="navbarText">
                  <ul class="navbar-nav me-auto mb-lg-0 ps-3">
                    <li class="nav-item">
                      <a href="{% url 'homepage' %}" class="nav-link">Homepage</a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'about' %}" class="nav-link">About</a>
                    </li>
                    {% if user.is_authenticated %}<li class="nav-item">
                      <a href="{% url 'spese:home' %}" class="nav-link">Resoconto</a>
                    </li>{% endif %}
                  </ul>
                  <!-- SETTINGS -->
                 <div class="btn-group dropdown-center">
                      <button type="button" class="btn btn-outline-secondary rounded ms-3" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-gear-fill"></i>
                      </button>
                      <ul class="dropdown-menu p-3">
                          <li class="pb-2">
                              <button class="darkModeToggle btn btn-light rounded" onclick="toggleDarkMode()">
                                <i class="darkModeIcon bi bi-brightness-high-fill"></i>
                              </button>
                          </li>
                          <li>
                              <button class="accessibilityModeToggle btn btn-outline-secondary rounded" onclick="setNewFont()">
                                <i class="accessibilityIcon bi bi-universal-access-circle"></i>
                              </button>
                          </li>
                      </ul>
                 </div>
                </div>
                <div class="btn-group d-none d-lg-block ms-2">
                    <!-- DIV DEL TASTO USER -->
                    <button type="button" class="btn btn-outline-secondary rounded" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        <i class="bi bi-person-fill"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item rounded" href="{% url 'users:register' %}">Register</a>
                        <li><a class="dropdown-item rounded" href="{% url 'users:login' %}">Login</a>
                            {% if user.is_authenticated %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form action="{% url 'users:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item rounded">Logout</button>
                            </form>
                        </li>
                        {% if user.is_staff %}
                        <li><a class="dropdown-item rounded" href="{% url 'admin:index' %}">Admin</a>
                            {% endif %}
                            {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            {% block content %}{% endblock %}
        </main>

        <footer class="container">
            <hr>
            <div class="float-end">
                <span id="weather"></span>
            </div>
            <p>&copy; 2024 Spesing &middot;
                <a href="#" data-bs-toggle="modal" data-bs-target="#ipmodal" onclick="getIpInfo()">Privacy</a>
            </p>
            <!-- Modal -->
            <div class="modal fade" id="ipmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Il tuo IP!</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Il tuo ip è <span id="ipaddress"></span>, ma qui nessuno ha voglia di salvare il dato<br>
                    Ribadiamo, <strong>TOP PRIVACY!</strong>
                  </div>
                </div>
              </div>
            </div>
        </footer>
    </body>
</html>

templates/homepage.html
{% extends "base.html"%}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="container pt-2 pb-4">
    <div class="py-4 px-4 mb-4 bg-body-tertiary text-body rounded-3">
      <div class="container-fluid">
            <!-- HERO -->
            <div class="my-3 text-center border-bottom">
                <figure class="d-flex align-center justify-content-center mb-4">
                    <img class="myLogo" src="{% static 'img/logo-spesing1.svg' %}" alt="Scritta pesing per completare il logo">
                    <img class="myLogoText inverted" src="{% static 'img/Banner-Spesing-Dark.png' %}" alt="Scritta pesing per completare il logo">
                </figure>
                <div class="col-lg-6 mx-auto">
                  <p class="lead mb-4">L'unico sito dove puoi gestire le tue GRANDI spese in modo comodo e ben organizzato</p>
                  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                    <a href="{% url 'users:register' %}" class="btn btn-secondary btn-lg px-4 me-sm-3">Registrati</a>
                    <a href="{% url 'users:login' %}" class="btn btn-outline-secondary btn-lg px-4">Accedi</a>
                  </div>
                </div>
                <div class="overflow-hidden hero_img">
                  <figure class="container">
                    <img src="{% static 'img/app-screen.png' %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
                  </figure>
                </div>
            </div>
      </div>
    </div>
    <div class="row align-items-md-stretch">
      <div class="col-md-6 mb-4 mb-md-0">
        <article class="h-100 p-4 bg-body-tertiary text-body rounded-3">
          <h4 class="fw-bold mb-3">Quanto è usata Spesing?</h4>
          <p class="m-2">Spese totali: <strong>{{ n_spese_totali }}</strong></p>
          <p class="m-2">Totale Speso: <strong>{{ totale_importo_spese }} €</strong></p>
        </article>
      </div>
      <div class="col-md-6">
        <div class="accordion" id="accordionExample">
            <article class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                Perché dovrei usare Spesing?
                </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <strong>E' UNA DOMANDA RETORICA!</strong><br>
                        Spesing è la miglior webapp di gestione spese al mondo!
                    </div>
                </div>
            </article>
            <article class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Cosa differenzia Spesing dai competitor?
                </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                    I nostri competitor sono molto bravi a rubarvi i dati <br>
                    Noi semplicemente non ne siamo ancora in grado <br>
                    E questo significa... <strong>TOP PRIVACY</strong>
                    </div>
                </div>
            </article>
            <article class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Spesing migliora la vita?
                </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                    Le domande retoriche <strong>ci piacciono un sacco</strong><br>
                    E' scentificamente provato che Spesing migliora tutti i voti <br>
                    Lo abbiamo testato noi per voi e... <br>
                    In Sviluppo Web abbiamo preso <strong>100!</strong>
                    </div>
                </div>
            </article>
          </div>
      </div>
    </div>
  </div>

{% endblock %}